// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ace.proto

// Generated code resulting from this package is imported into both the sidecar and linkage

package rpc

import (
	fmt "fmt"
	messaging "github.com/Axway/ace-golang-sdk/messaging"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Service info specified in business logic and passed to sidecar for registration.
type ServiceInfo struct {
	ServiceName          string   `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	ServiceVersion       string   `protobuf:"bytes,2,opt,name=service_version,json=serviceVersion,proto3" json:"service_version,omitempty"`
	ServiceDescription   string   `protobuf:"bytes,3,opt,name=service_description,json=serviceDescription,proto3" json:"service_description,omitempty"`
	ServiceHost          string   `protobuf:"bytes,4,opt,name=service_host,json=serviceHost,proto3" json:"service_host,omitempty"`
	ServicePort          uint32   `protobuf:"varint,5,opt,name=service_port,json=servicePort,proto3" json:"service_port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceInfo) Reset()         { *m = ServiceInfo{} }
func (m *ServiceInfo) String() string { return proto.CompactTextString(m) }
func (*ServiceInfo) ProtoMessage()    {}
func (*ServiceInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_671d051cacda6b9d, []int{0}
}

func (m *ServiceInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceInfo.Unmarshal(m, b)
}
func (m *ServiceInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceInfo.Marshal(b, m, deterministic)
}
func (m *ServiceInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceInfo.Merge(m, src)
}
func (m *ServiceInfo) XXX_Size() int {
	return xxx_messageInfo_ServiceInfo.Size(m)
}
func (m *ServiceInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceInfo proto.InternalMessageInfo

func (m *ServiceInfo) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *ServiceInfo) GetServiceVersion() string {
	if m != nil {
		return m.ServiceVersion
	}
	return ""
}

func (m *ServiceInfo) GetServiceDescription() string {
	if m != nil {
		return m.ServiceDescription
	}
	return ""
}

func (m *ServiceInfo) GetServiceHost() string {
	if m != nil {
		return m.ServiceHost
	}
	return ""
}

func (m *ServiceInfo) GetServicePort() uint32 {
	if m != nil {
		return m.ServicePort
	}
	return 0
}

// Root structure for all STOMP messages.
type Message struct {
	// Unique ID of the message containing this payload.
	UUID string `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
	// Unique ID of the message that was processed which resulted in this message.
	Parent_UUID string `protobuf:"bytes,2,opt,name=parent_UUID,json=parentUUID,proto3" json:"parent_UUID,omitempty"`
	// Term and upper bound sequence information if the parent message resulted in multiple children.
	SequenceTerm       uint64 `protobuf:"varint,3,opt,name=sequence_term,json=sequenceTerm,proto3" json:"sequence_term,omitempty"`
	SequenceUpperBound uint64 `protobuf:"varint,4,opt,name=sequence_upper_bound,json=sequenceUpperBound,proto3" json:"sequence_upper_bound,omitempty"`
	// UUID tied to choreography name.
	CHN_UUID string `protobuf:"bytes,5,opt,name=CHN_UUID,json=CHNUUID,proto3" json:"CHN_UUID,omitempty"`
	// UUID for this specific execution of the choreography.
	CHX_UUID             string                     `protobuf:"bytes,6,opt,name=CHX_UUID,json=CHXUUID,proto3" json:"CHX_UUID,omitempty"`
	Pattern              *StepPattern               `protobuf:"bytes,7,opt,name=pattern,proto3" json:"pattern,omitempty"`
	MetaData             map[string]string          `protobuf:"bytes,8,rep,name=meta_data,json=metaData,proto3" json:"meta_data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	BusinessMessage      *messaging.BusinessMessage `protobuf:"bytes,9,opt,name=business_message,json=businessMessage,proto3" json:"business_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_671d051cacda6b9d, []int{1}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetUUID() string {
	if m != nil {
		return m.UUID
	}
	return ""
}

func (m *Message) GetParent_UUID() string {
	if m != nil {
		return m.Parent_UUID
	}
	return ""
}

func (m *Message) GetSequenceTerm() uint64 {
	if m != nil {
		return m.SequenceTerm
	}
	return 0
}

func (m *Message) GetSequenceUpperBound() uint64 {
	if m != nil {
		return m.SequenceUpperBound
	}
	return 0
}

func (m *Message) GetCHN_UUID() string {
	if m != nil {
		return m.CHN_UUID
	}
	return ""
}

func (m *Message) GetCHX_UUID() string {
	if m != nil {
		return m.CHX_UUID
	}
	return ""
}

func (m *Message) GetPattern() *StepPattern {
	if m != nil {
		return m.Pattern
	}
	return nil
}

func (m *Message) GetMetaData() map[string]string {
	if m != nil {
		return m.MetaData
	}
	return nil
}

func (m *Message) GetBusinessMessage() *messaging.BusinessMessage {
	if m != nil {
		return m.BusinessMessage
	}
	return nil
}

type StepPattern struct {
	// Address of the name and version of the service this message is intended for.
	ServiceName    string `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	ServiceVersion string `protobuf:"bytes,2,opt,name=service_version,json=serviceVersion,proto3" json:"service_version,omitempty"`
	// Placeholder fields for payload transformation, routing, and validation.
	Validation     string `protobuf:"bytes,3,opt,name=validation,proto3" json:"validation,omitempty"`
	Evaluation     string `protobuf:"bytes,4,opt,name=evaluation,proto3" json:"evaluation,omitempty"`
	Transformation string `protobuf:"bytes,5,opt,name=transformation,proto3" json:"transformation,omitempty"`
	// Recursion of StepPattern to provide the overall structure of the choreography.
	Child                []*StepPattern `protobuf:"bytes,6,rep,name=child,proto3" json:"child,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *StepPattern) Reset()         { *m = StepPattern{} }
func (m *StepPattern) String() string { return proto.CompactTextString(m) }
func (*StepPattern) ProtoMessage()    {}
func (*StepPattern) Descriptor() ([]byte, []int) {
	return fileDescriptor_671d051cacda6b9d, []int{2}
}

func (m *StepPattern) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StepPattern.Unmarshal(m, b)
}
func (m *StepPattern) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StepPattern.Marshal(b, m, deterministic)
}
func (m *StepPattern) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StepPattern.Merge(m, src)
}
func (m *StepPattern) XXX_Size() int {
	return xxx_messageInfo_StepPattern.Size(m)
}
func (m *StepPattern) XXX_DiscardUnknown() {
	xxx_messageInfo_StepPattern.DiscardUnknown(m)
}

var xxx_messageInfo_StepPattern proto.InternalMessageInfo

func (m *StepPattern) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *StepPattern) GetServiceVersion() string {
	if m != nil {
		return m.ServiceVersion
	}
	return ""
}

func (m *StepPattern) GetValidation() string {
	if m != nil {
		return m.Validation
	}
	return ""
}

func (m *StepPattern) GetEvaluation() string {
	if m != nil {
		return m.Evaluation
	}
	return ""
}

func (m *StepPattern) GetTransformation() string {
	if m != nil {
		return m.Transformation
	}
	return ""
}

func (m *StepPattern) GetChild() []*StepPattern {
	if m != nil {
		return m.Child
	}
	return nil
}

// Simple confirmation structure for RPC calls.
type Receipt struct {
	IsOk                 bool     `protobuf:"varint,1,opt,name=is_ok,json=isOk,proto3" json:"is_ok,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Receipt) Reset()         { *m = Receipt{} }
func (m *Receipt) String() string { return proto.CompactTextString(m) }
func (*Receipt) ProtoMessage()    {}
func (*Receipt) Descriptor() ([]byte, []int) {
	return fileDescriptor_671d051cacda6b9d, []int{3}
}

func (m *Receipt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Receipt.Unmarshal(m, b)
}
func (m *Receipt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Receipt.Marshal(b, m, deterministic)
}
func (m *Receipt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Receipt.Merge(m, src)
}
func (m *Receipt) XXX_Size() int {
	return xxx_messageInfo_Receipt.Size(m)
}
func (m *Receipt) XXX_DiscardUnknown() {
	xxx_messageInfo_Receipt.DiscardUnknown(m)
}

var xxx_messageInfo_Receipt proto.InternalMessageInfo

func (m *Receipt) GetIsOk() bool {
	if m != nil {
		return m.IsOk
	}
	return false
}

func (m *Receipt) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*ServiceInfo)(nil), "rpc.ServiceInfo")
	proto.RegisterType((*Message)(nil), "rpc.Message")
	proto.RegisterMapType((map[string]string)(nil), "rpc.Message.MetaDataEntry")
	proto.RegisterType((*StepPattern)(nil), "rpc.StepPattern")
	proto.RegisterType((*Receipt)(nil), "rpc.Receipt")
}

func init() { proto.RegisterFile("ace.proto", fileDescriptor_671d051cacda6b9d) }

var fileDescriptor_671d051cacda6b9d = []byte{
	// 621 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x94, 0xdf, 0x4e, 0x13, 0x41,
	0x14, 0xc6, 0x59, 0xda, 0xd2, 0xf6, 0xb4, 0xfc, 0xc9, 0x80, 0xc9, 0xda, 0x0b, 0xad, 0x25, 0xc1,
	0x6a, 0xc2, 0x96, 0xa0, 0x89, 0x46, 0xaf, 0x28, 0x90, 0x40, 0x14, 0x6c, 0x16, 0x31, 0xc4, 0x9b,
	0xcd, 0x74, 0xf7, 0x50, 0x26, 0xed, 0xce, 0xac, 0x33, 0xd3, 0x6a, 0xdf, 0xc0, 0x07, 0xf2, 0x41,
	0x7c, 0x0d, 0xdf, 0xc2, 0xcc, 0xcc, 0x2e, 0x14, 0xbc, 0xf5, 0x6e, 0xcf, 0xf7, 0xfd, 0xd2, 0x6f,
	0xce, 0x99, 0xd3, 0x81, 0x3a, 0x8d, 0x31, 0xc8, 0xa4, 0xd0, 0x82, 0x94, 0x64, 0x16, 0xb7, 0xd6,
	0x86, 0x53, 0xc5, 0x38, 0x2a, 0xe5, 0xc4, 0xce, 0x6f, 0x0f, 0x1a, 0x17, 0x28, 0x67, 0x2c, 0xc6,
	0x53, 0x7e, 0x2d, 0xc8, 0x33, 0x68, 0x2a, 0x57, 0x46, 0x9c, 0xa6, 0xe8, 0x7b, 0x6d, 0xaf, 0x5b,
	0x0f, 0x1b, 0xb9, 0x76, 0x4e, 0x53, 0x24, 0xcf, 0x61, 0xbd, 0x40, 0x66, 0x28, 0x15, 0x13, 0xdc,
	0x5f, 0xb6, 0xd4, 0x5a, 0x2e, 0x7f, 0x71, 0x2a, 0xe9, 0xc1, 0x66, 0x01, 0x26, 0xa8, 0x62, 0xc9,
	0x32, 0x6d, 0xe0, 0x92, 0x85, 0x49, 0x6e, 0x1d, 0xdd, 0x39, 0x8b, 0xe1, 0x37, 0x42, 0x69, 0xbf,
	0x7c, 0x2f, 0xfc, 0x44, 0x28, 0xbd, 0x88, 0x64, 0x42, 0x6a, 0xbf, 0xd2, 0xf6, 0xba, 0xab, 0xb7,
	0xc8, 0x40, 0x48, 0xdd, 0xf9, 0x55, 0x82, 0xea, 0x19, 0x2a, 0x45, 0x47, 0x48, 0x08, 0x94, 0x2f,
	0x2f, 0x4f, 0x8f, 0xf2, 0x36, 0xec, 0x37, 0x79, 0x0a, 0x8d, 0x8c, 0x4a, 0xe4, 0x3a, 0xb2, 0x96,
	0x3b, 0x3b, 0x38, 0xc9, 0x02, 0xdb, 0xb0, 0xaa, 0xf0, 0xdb, 0x14, 0x79, 0x8c, 0x91, 0x46, 0x99,
	0xda, 0x13, 0x97, 0xc3, 0x66, 0x21, 0x7e, 0x46, 0x99, 0x92, 0x3d, 0xd8, 0xba, 0x85, 0xa6, 0x59,
	0x86, 0x32, 0x1a, 0x8a, 0x29, 0x4f, 0xec, 0x99, 0xcb, 0xa6, 0x3b, 0xe7, 0x5d, 0x1a, 0xab, 0x6f,
	0x1c, 0xf2, 0x18, 0x6a, 0x87, 0x27, 0xe7, 0x2e, 0xb4, 0x62, 0x43, 0xab, 0x87, 0x27, 0xe7, 0x36,
	0xd1, 0x5a, 0x57, 0xce, 0x5a, 0x29, 0xac, 0x2b, 0x6b, 0xbd, 0x84, 0x6a, 0x46, 0xb5, 0x46, 0xc9,
	0xfd, 0x6a, 0xdb, 0xeb, 0x36, 0xf6, 0x37, 0x02, 0x99, 0xc5, 0xc1, 0x85, 0xc6, 0x6c, 0xe0, 0xf4,
	0xb0, 0x00, 0xc8, 0x1b, 0xa8, 0xa7, 0xa8, 0x69, 0x94, 0x50, 0x4d, 0xfd, 0x5a, 0xbb, 0xd4, 0x6d,
	0xec, 0xb7, 0x2c, 0x9d, 0x8f, 0x23, 0x38, 0x43, 0x4d, 0x8f, 0xa8, 0xa6, 0xc7, 0x5c, 0xcb, 0x79,
	0x58, 0x4b, 0xf3, 0x92, 0x1c, 0xc3, 0x46, 0xb1, 0x17, 0x51, 0xea, 0x58, 0xbf, 0x6e, 0xd3, 0x5a,
	0x81, 0xab, 0x19, 0x1f, 0x05, 0xfd, 0x1c, 0xc9, 0x7f, 0x2d, 0x5c, 0x1f, 0xde, 0x17, 0x5a, 0xef,
	0x61, 0xf5, 0x5e, 0x02, 0xd9, 0x80, 0xd2, 0x18, 0xe7, 0xf9, 0xf4, 0xcd, 0x27, 0xd9, 0x82, 0xca,
	0x8c, 0x4e, 0xa6, 0x98, 0x8f, 0xdd, 0x15, 0xef, 0x96, 0xdf, 0x7a, 0x9d, 0x3f, 0x66, 0x13, 0xef,
	0xba, 0xfa, 0xaf, 0x9b, 0xf8, 0x04, 0x60, 0x46, 0x27, 0x2c, 0xa1, 0x0b, 0x0b, 0xb8, 0xa0, 0x18,
	0x1f, 0xcd, 0x49, 0x9c, 0xef, 0xd6, 0x6e, 0x41, 0x21, 0x3b, 0xb0, 0xa6, 0x25, 0xe5, 0xea, 0x5a,
	0xc8, 0xd4, 0x31, 0xee, 0x02, 0x1f, 0xa8, 0x64, 0x07, 0x2a, 0xf1, 0x0d, 0x9b, 0x24, 0xfe, 0x8a,
	0x1d, 0xfe, 0xbf, 0x57, 0xe5, 0xec, 0xce, 0x6b, 0xa8, 0x86, 0x18, 0x23, 0xcb, 0x34, 0xd9, 0x84,
	0x0a, 0x53, 0x91, 0x18, 0xdb, 0xfe, 0x6a, 0x61, 0x99, 0xa9, 0x4f, 0x63, 0x33, 0x25, 0x94, 0x52,
	0xc8, 0x62, 0x4a, 0xb6, 0xd8, 0xbf, 0x86, 0xea, 0x47, 0xc6, 0xc7, 0x66, 0xaf, 0xf7, 0xa0, 0x19,
	0xe2, 0x88, 0x29, 0x2d, 0x5d, 0x70, 0x9e, 0x74, 0xf7, 0x47, 0x6e, 0x35, 0xad, 0x92, 0xa7, 0x74,
	0x96, 0xc8, 0x0b, 0xa8, 0x84, 0x38, 0xa1, 0x73, 0xd2, 0x5c, 0xdc, 0x88, 0x87, 0x58, 0xd7, 0xdb,
	0xf3, 0xfa, 0x1f, 0xe0, 0x51, 0x2c, 0xd2, 0x80, 0xfe, 0xf8, 0x4e, 0xe7, 0x81, 0x79, 0x3f, 0x54,
	0x32, 0x36, 0x58, 0xbf, 0x76, 0x10, 0xe3, 0xc0, 0x3c, 0x1b, 0x03, 0xef, 0xeb, 0xf6, 0x88, 0xe9,
	0x9b, 0xe9, 0x30, 0x88, 0x45, 0xda, 0x3b, 0x30, 0x64, 0x8f, 0xc6, 0xb8, 0x3b, 0x12, 0x13, 0xca,
	0x47, 0xbb, 0x2a, 0x19, 0xf7, 0x64, 0x16, 0xff, 0xf4, 0x96, 0x86, 0x2b, 0xf6, 0x9d, 0x79, 0xf5,
	0x37, 0x00, 0x00, 0xff, 0xff, 0xc6, 0x28, 0x6b, 0x32, 0x89, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LinkageClient is the client API for Linkage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LinkageClient interface {
	Registration(ctx context.Context, in *ServiceInfo, opts ...grpc.CallOption) (*Receipt, error)
	Relay(ctx context.Context, opts ...grpc.CallOption) (Linkage_RelayClient, error)
}

type linkageClient struct {
	cc *grpc.ClientConn
}

func NewLinkageClient(cc *grpc.ClientConn) LinkageClient {
	return &linkageClient{cc}
}

func (c *linkageClient) Registration(ctx context.Context, in *ServiceInfo, opts ...grpc.CallOption) (*Receipt, error) {
	out := new(Receipt)
	err := c.cc.Invoke(ctx, "/rpc.Linkage/Registration", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *linkageClient) Relay(ctx context.Context, opts ...grpc.CallOption) (Linkage_RelayClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Linkage_serviceDesc.Streams[0], "/rpc.Linkage/Relay", opts...)
	if err != nil {
		return nil, err
	}
	x := &linkageRelayClient{stream}
	return x, nil
}

type Linkage_RelayClient interface {
	Send(*Message) error
	Recv() (*Receipt, error)
	grpc.ClientStream
}

type linkageRelayClient struct {
	grpc.ClientStream
}

func (x *linkageRelayClient) Send(m *Message) error {
	return x.ClientStream.SendMsg(m)
}

func (x *linkageRelayClient) Recv() (*Receipt, error) {
	m := new(Receipt)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// LinkageServer is the server API for Linkage service.
type LinkageServer interface {
	Registration(context.Context, *ServiceInfo) (*Receipt, error)
	Relay(Linkage_RelayServer) error
}

func RegisterLinkageServer(s *grpc.Server, srv LinkageServer) {
	s.RegisterService(&_Linkage_serviceDesc, srv)
}

func _Linkage_Registration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinkageServer).Registration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Linkage/Registration",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinkageServer).Registration(ctx, req.(*ServiceInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Linkage_Relay_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(LinkageServer).Relay(&linkageRelayServer{stream})
}

type Linkage_RelayServer interface {
	Send(*Receipt) error
	Recv() (*Message, error)
	grpc.ServerStream
}

type linkageRelayServer struct {
	grpc.ServerStream
}

func (x *linkageRelayServer) Send(m *Receipt) error {
	return x.ServerStream.SendMsg(m)
}

func (x *linkageRelayServer) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Linkage_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.Linkage",
	HandlerType: (*LinkageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Registration",
			Handler:    _Linkage_Registration_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Relay",
			Handler:       _Linkage_Relay_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "ace.proto",
}
