// Code generated by protoc-gen-go. DO NOT EDIT.
// source: business.proto

package messaging

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Payload struct {
	// Is the payload the actual payload, or a claimcheck location reference to an object store?
	LocationReference bool `protobuf:"varint,1,opt,name=location_reference,json=locationReference,proto3" json:"location_reference,omitempty"`
	// Payload or a claimcheck reference to an object store.
	Body                 []byte   `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Payload) Reset()         { *m = Payload{} }
func (m *Payload) String() string { return proto.CompactTextString(m) }
func (*Payload) ProtoMessage()    {}
func (*Payload) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb4ce4f7d40c421f, []int{0}
}

func (m *Payload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payload.Unmarshal(m, b)
}
func (m *Payload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payload.Marshal(b, m, deterministic)
}
func (m *Payload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payload.Merge(m, src)
}
func (m *Payload) XXX_Size() int {
	return xxx_messageInfo_Payload.Size(m)
}
func (m *Payload) XXX_DiscardUnknown() {
	xxx_messageInfo_Payload.DiscardUnknown(m)
}

var xxx_messageInfo_Payload proto.InternalMessageInfo

func (m *Payload) GetLocationReference() bool {
	if m != nil {
		return m.LocationReference
	}
	return false
}

func (m *Payload) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type BusinessMessage struct {
	MetaData             map[string]string `protobuf:"bytes,1,rep,name=meta_data,json=metaData,proto3" json:"meta_data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Payload              *Payload          `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *BusinessMessage) Reset()         { *m = BusinessMessage{} }
func (m *BusinessMessage) String() string { return proto.CompactTextString(m) }
func (*BusinessMessage) ProtoMessage()    {}
func (*BusinessMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb4ce4f7d40c421f, []int{1}
}

func (m *BusinessMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BusinessMessage.Unmarshal(m, b)
}
func (m *BusinessMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BusinessMessage.Marshal(b, m, deterministic)
}
func (m *BusinessMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BusinessMessage.Merge(m, src)
}
func (m *BusinessMessage) XXX_Size() int {
	return xxx_messageInfo_BusinessMessage.Size(m)
}
func (m *BusinessMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_BusinessMessage.DiscardUnknown(m)
}

var xxx_messageInfo_BusinessMessage proto.InternalMessageInfo

func (m *BusinessMessage) GetMetaData() map[string]string {
	if m != nil {
		return m.MetaData
	}
	return nil
}

func (m *BusinessMessage) GetPayload() *Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func init() {
	proto.RegisterType((*Payload)(nil), "messaging.Payload")
	proto.RegisterType((*BusinessMessage)(nil), "messaging.BusinessMessage")
	proto.RegisterMapType((map[string]string)(nil), "messaging.BusinessMessage.MetaDataEntry")
}

func init() { proto.RegisterFile("business.proto", fileDescriptor_fb4ce4f7d40c421f) }

var fileDescriptor_fb4ce4f7d40c421f = []byte{
	// 292 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x91, 0xcb, 0x4e, 0xf3, 0x30,
	0x10, 0x85, 0xe5, 0xf6, 0xff, 0x69, 0xe3, 0x52, 0x2e, 0x16, 0x8b, 0x0a, 0x36, 0x55, 0x57, 0x41,
	0xa2, 0xae, 0x54, 0x36, 0x08, 0x56, 0x44, 0x74, 0x47, 0xa5, 0xc8, 0x3b, 0xd8, 0x54, 0x13, 0x67,
	0x08, 0x51, 0x12, 0xbb, 0x8a, 0x1d, 0x20, 0xcf, 0xc7, 0x8b, 0xa1, 0xb8, 0x49, 0xb9, 0xec, 0x66,
	0x34, 0x33, 0xe7, 0x3b, 0xc7, 0xa6, 0x47, 0x51, 0x65, 0x52, 0x85, 0xc6, 0xf0, 0x6d, 0xa9, 0xad,
	0x66, 0x5e, 0x81, 0xc6, 0x40, 0x92, 0xaa, 0x64, 0xf6, 0x48, 0x07, 0x21, 0xd4, 0xb9, 0x86, 0x98,
	0xcd, 0x29, 0xcb, 0xb5, 0x04, 0x9b, 0x6a, 0xb5, 0x29, 0xf1, 0x05, 0x4b, 0x54, 0x12, 0x27, 0x64,
	0x4a, 0xfc, 0xa1, 0x38, 0xed, 0x26, 0xa2, 0x1b, 0x30, 0x46, 0xff, 0x45, 0x3a, 0xae, 0x27, 0xbd,
	0x29, 0xf1, 0x0f, 0x85, 0xab, 0x67, 0x9f, 0x84, 0x1e, 0x07, 0x2d, 0x6b, 0xed, 0x18, 0xc8, 0x56,
	0xd4, 0x2b, 0xd0, 0xc2, 0x26, 0x06, 0x0b, 0x13, 0x32, 0xed, 0xfb, 0xa3, 0xa5, 0xcf, 0xf7, 0x06,
	0xf8, 0x9f, 0x75, 0xbe, 0x46, 0x0b, 0x0f, 0x60, 0x61, 0xa5, 0x6c, 0x59, 0x8b, 0x61, 0xd1, 0xb6,
	0xec, 0x8a, 0x0e, 0xb6, 0x3b, 0xa3, 0x8e, 0x38, 0x5a, 0xb2, 0x1f, 0x22, 0x6d, 0x04, 0xd1, 0xad,
	0x9c, 0xdf, 0xd1, 0xf1, 0x2f, 0x21, 0x76, 0x42, 0xfb, 0x19, 0xd6, 0x2e, 0x8d, 0x27, 0x9a, 0x92,
	0x9d, 0xd1, 0xff, 0x6f, 0x90, 0x57, 0xe8, 0xe4, 0x3c, 0xb1, 0x6b, 0x6e, 0x7b, 0x37, 0x24, 0x78,
	0xa2, 0x17, 0x52, 0x17, 0x1c, 0x3e, 0xde, 0xa1, 0xe6, 0x20, 0x91, 0x9b, 0x38, 0xfb, 0x86, 0x05,
	0xe3, 0xce, 0x72, 0xd8, 0x3c, 0x66, 0x48, 0x9e, 0x2f, 0x93, 0xd4, 0xbe, 0x56, 0x11, 0x97, 0xba,
	0x58, 0xdc, 0x37, 0x47, 0x0b, 0x90, 0x38, 0x4f, 0x74, 0x0e, 0x2a, 0x99, 0x9b, 0x38, 0x5b, 0xec,
	0x6f, 0xa3, 0x03, 0xf7, 0x01, 0xd7, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xda, 0x1e, 0x94, 0xaf,
	0x92, 0x01, 0x00, 0x00,
}
